#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  3 10:40:03 2024

@author: coledlocks
"""

import numpy as np 
def load_data(file, fs):
    data = np.loadtxt(file) * 5/1023
    time = np.arange(0, len(data)/fs, 1/fs)
    return data, time

def trim_data_to_5_seconds(data):
    trimmed_data = data[:2500]
    return trimmed_data
